version: "3.7"
services:
  spamassassin-parser:
    restart: unless-stopped
    container_name: spamassassin-parser
    networks:
      - spamassassin_dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPAMASSASSIN_INPUT: "data/input"
      - SPAMASSASSIN_OUTPUT: "data/result"
      - SPAMASSASSIN_ARCHIVE: "data/archive"
      - SPAMASSASSIN_RECEIVE_ERRORS: "true"

    volumes:
      - ./data/input:/data/input
      - ./data/result:/data/result
      - ./data/archive:/data/archive


volumes:
  input:
    driver: local
  result:
    driver: local
  archive:
    driver: local

networks:
  spamassassin_dev:
    driver: bridge